# Generated by Django 4.1.3 on 2022-11-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moname', models.CharField(default='Art', max_length=64)),
                ('montype', models.CharField(default='Art', max_length=25)),
                ('cr', models.IntegerField(default=1)),
                ('ca', models.IntegerField(default=10)),
                ('hp', models.IntegerField(default=1)),
                ('drs', models.CharField(default='None', max_length=250)),
                ('speed', models.IntegerField(default=6)),
                ('str', models.IntegerField(default=0)),
                ('dex', models.IntegerField(default=0)),
                ('con', models.IntegerField(default=0)),
                ('int', models.IntegerField(default=0)),
                ('wis', models.IntegerField(default=0)),
                ('cha', models.IntegerField(default=0)),
                ('pp', models.IntegerField(default=10)),
                ('skill_1', models.CharField(default='ª', max_length=250)),
                ('skill_2', models.CharField(default='ª', max_length=250)),
                ('skill_3', models.CharField(default='ª', max_length=250)),
                ('action_1', models.CharField(default='Attack 1', max_length=250)),
                ('action_2', models.CharField(default='Attack 2', max_length=250)),
                ('action_3', models.CharField(default='Attack 3', max_length=250)),
                ('spells', models.TextField(default='Mage Spell list')),
            ],
        ),
    ]
