# Generated by Django 4.1.3 on 2022-12-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='action_1',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='monster',
            name='action_2',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='monster',
            name='action_3',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='monster',
            name='moname',
            field=models.CharField(default='Monster', max_length=64),
        ),
        migrations.AlterField(
            model_name='monster',
            name='montype',
            field=models.CharField(default='Medium Humanoid', max_length=25),
        ),
        migrations.AlterField(
            model_name='monster',
            name='skill_1',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='monster',
            name='skill_2',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='monster',
            name='skill_3',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='monster',
            name='spells',
            field=models.TextField(default='None'),
        ),
    ]
