# Generated by Django 4.1.3 on 2022-11-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewCharacter',
            new_name='Character',
        ),
    ]
