# Generated by Django 4.1.3 on 2022-11-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_rename_newcharacter_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ca',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='cha',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='character',
            name='charclass',
            field=models.CharField(default='Art', max_length=25),
        ),
        migrations.AddField(
            model_name='character',
            name='charname',
            field=models.CharField(default='Art', max_length=64),
        ),
        migrations.AddField(
            model_name='character',
            name='con',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='character',
            name='dex',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='int',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='playername',
            field=models.CharField(default='Art', max_length=64),
        ),
        migrations.AddField(
            model_name='character',
            name='pp',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(default='Art', max_length=25),
        ),
        migrations.AddField(
            model_name='character',
            name='str',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='character',
            name='wis',
            field=models.IntegerField(default=8),
        ),
    ]
