# Generated by Django 4.1.3 on 2022-11-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_character_ca_character_cha_character_charclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='cha',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='con',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='dex',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='int',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='str',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='wis',
            field=models.IntegerField(default=0),
        ),
    ]
