# Generated by Django 4.1.3 on 2022-12-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rte', '0002_remove_rte_tabledice_alter_rte_tablename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rte',
            name='tablename',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
